name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.12-slim

    services:
      db:
        image: postgres:17
        env:
          POSTGRES_DB: realestatepriceforecast_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: kamil

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: make Lint

      - name: Test
        run: make test
        env:
          continue
