services:
  web:
    build:
      context: ../RealEstatePriceForecastBackend  # Poprawna ścieżka do backendu
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../RealEstatePriceForecastBackend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=realestatepriceforecast_db
      - DB_USER=postgres
      - DB_PASSWORD=kamil
      - DB_HOST=db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: realestatepriceforecast_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kamil
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ../frontend  # Ścieżka do frontend Dockerfile
    ports:
      - "5173:5173"  # Port dla aplikacji Vue.js

volumes:
  postgres_data:
