services:
  web:
    build:
      context: ../RealEstatePriceForecastBackend
    volumes:
      - ../RealEstatePriceForecastBackend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=${SQL_NAME}
      - DB_USER=${SQL_USER}
      - DB_PASSWORD=${SQL_PASSWORD}
      - DB_HOST=${HOST}

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${SQL_NAME}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${PORT}:5432"

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:5173"

volumes:
  postgres_data: