name: Quality Assurance
on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "master" ]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.12-slim

    services:
      db:
        image: postgres:17
        env:
          POSTGRES_DB: realestatepriceforecast_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: kamil

    steps:
      - uses: actions/checkout@v2

      - name: Install PostgreSQL Development Package
        run: |
          apt-get update && apt-get install -y libpq-dev

      - name: Install Dependencies
        run: |
          cd RealEstatePriceForecastBackend
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Lint
        run: |
          cd RealEstatePriceForecastBackend
          make Lint

      - name: Run Tests
        run: |
          cd RealEstatePriceForecastBackend
          python manage.py test
